export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  groqApiKey: process.env.GROQ_API_KEY ?? "",
  pythonBrainUrl: process.env.AUREVION_PYTHON_BRAIN_URL ?? "",
  aurevionClientApiKey: process.env.AUREVION_CLIENT_API_KEY ?? "",
  groqModel: process.env.GROQ_MODEL ?? "openai/gpt-oss-20b",
  groqVisionModel: process.env.GROQ_VISION_MODEL ?? "qwen/qwen3.6-27b",
  groqProVisionModel: process.env.GROQ_PRO_VISION_MODEL ?? "qwen/qwen3.8-27b",
  officialSiteUrl: process.env.AUREVION_OFFICIAL_SITE_URL ?? "https://aurevion-two.vercel.app",
  allowedOrigins: (process.env.AUREVION_ALLOWED_ORIGINS ?? "https://aurevion-two.vercel.app,http://localhost:3000").split(",").map(origin => origin.trim()).filter(Boolean),
  freeMessageLimit: Number(process.env.AUREVION_FREE_MESSAGE_LIMIT ?? (process.env.NODE_ENV === "test" ? 25 : 0)),
  proMessageLimit: Number(process.env.AUREVION_PRO_MESSAGE_LIMIT ?? 500),
  geminiApiKey: process.env.GEMINI_API_KEY ?? "",
  geminiImageModel: process.env.GEMINI_IMAGE_MODEL ?? "gemini-3.1-flash-image",
  geminiProImageModel: process.env.GEMINI_PRO_IMAGE_MODEL ?? "gemini-3-pro-image",
  freeImageLimit: Number(process.env.AUREVION_FREE_IMAGE_LIMIT ?? 5),
  proImageLimit: Number(process.env.AUREVION_PRO_IMAGE_LIMIT ?? 100),
  paytabsProfileId: process.env.PAYTABS_PROFILE_ID ?? "",
  paytabsServerKey: process.env.PAYTABS_SERVER_KEY ?? "",
  paytabsEndpoint: process.env.PAYTABS_ENDPOINT ?? "https://secure.paytabs.com",
  paytabsCallbackUrl: process.env.PAYTABS_CALLBACK_URL ?? "",
  paytabsReturnUrl: process.env.PAYTABS_RETURN_URL ?? "",
  walletCurrency: process.env.WALLET_CURRENCY ?? "SAR",
  chatPrice: process.env.AUREVION_CHAT_PRICE ?? "0.10",
  imagePrice: process.env.AUREVION_IMAGE_PRICE ?? "0.50",
  walletEnforce: process.env.AUREVION_WALLET_ENFORCE === "true",
  pollinationsApiKey: process.env.POLLINATIONS_API_KEY ?? "",
  pollinationsEndpoint: process.env.POLLINATIONS_ENDPOINT ?? "https://image.pollinations.ai/prompt",
  pollinationsModel: process.env.POLLINATIONS_MODEL ?? "flux",
  elevenLabsApiKey: process.env.ELEVENLABS_API_KEY ?? "",
  googleApiKey: process.env.GOOGLE_API_KEY ?? "",
  googleSearchCx: process.env.GOOGLE_SEARCH_CX ?? "",
  braveApiKey: process.env.BRAVE_SEARCH_API_KEY ?? process.env.BING_API_KEY ?? "",
  searxngUrl: process.env.SEARXNG_URL ?? "",
  yandexApiKey: process.env.YANDEX_API_KEY ?? "",
  yandexUser: process.env.YANDEX_USER ?? "",
};
